version: '3'
services:
  toposoid-common-nlp-english-web:
    image: toposoid-common-nlp-english-web:0.6-SNAPSHOT
    tty: true
    environment:
      - TOPOSOID_SYNONYM_NOUN_SIMILARITY_THRESHHOLD_EN=0.52
      - TOPOSOID_SYNONYM_VERB_SIMILARITY_THRESHHOLD_EN=0.52
      - TOPOSOID_WORD2VEC_SIMILARITY_THRESHHOLD_EN=0.78
      - TOPOSOID_SENTENCEBERT_MODEL_EN=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - TOPOSOID_SPACY_MODEL_EN=en_core_web_lg
      - SENTENCE_TRANSFORMERS_HOME=./models
    ports:
      - 9008:9008
